version: "3.3"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#

services:
  production_database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./production_database_data/db/db.dump.sql:/docker-entrypoint-initdb.d/db.dump.sql
    environment:
      - POSTGRES_DB=${PRODUCTION_DATABASE_DB}
      - POSTGRES_USER=${PRODUCTION_DATABASE_USER}
      - POSTGRES_PASSWORD=${PRODUCTION_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${PRODUCTION_DATABASE_PORT}:5432"


  default_database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./default_database_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"

  test_database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./test_database_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TEST_DATABASE_DB}
      - POSTGRES_USER=${TEST_DATABASE_USER}
      - POSTGRES_PASSWORD=${TEST_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${TEST_DATABASE_PORT}:5432"
