Controller:
  model_structure: null
MFVI:
  hexa_rank: 150
  hexa_std: 1
  iterations: 3
  normalize_weight: true
  quad_rank: 150
  quad_std: 1
  tag_dim: 150
  use_hexalinear: false
  use_quadrilinear: false
  use_second_order: false
  use_third_order: false
  window_size: 1
ReinforcementTrainer:
  controller_learning_rate: 0.1
  controller_optimizer: SGD
  distill_mode: false
  optimizer: SGD
  sentence_level_batch: true
anneal_factor: 2
ast:
  Corpus: SEMEVAL14_LAPTOP:ColumnCorpus-1
  ColumnCorpus-1:
    data_folder: E:\BP\data\private\gamereviews
    column_format:
      0: text
      1: ast
    tag_to_bioes: ast
  tag_dictionary: resources/taggers/ast_tags.pkl
atis:
  Corpus: ATIS-EN:ATIS-TR:ATIS-HI
chunk:
  Corpus: CONLL_03:CONLL_03_GERMAN
embeddings:
  FastCharacterEmbeddings:
    char_embedding_dim: 25
    hidden_size_char: 25
  FastWordEmbeddings-0:
    embeddings: en
    freeze: true
  FlairEmbeddings-0:
    model: en-forward
  FlairEmbeddings-1:
    model: en-backward
  FlairEmbeddings-2:
    model: multi-forward
  FlairEmbeddings-3:
    model: multi-backward
  TransformerWordEmbeddings-0:
    layers: -1,-2,-3,-4
    model: ufal/robeczech-base
    pooling_operation: first
  TransformerWordEmbeddings-1:
    layers: -1,-2,-3,-4
    model: bert-base-cased
    pooling_operation: first
  TransformerWordEmbeddings-2:
    layers: -1,-2,-3,-4
    model: bert-base-multilingual-cased
    pooling_operation: first
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 800
    sentence_loss: true
    use_crf: true
model_name: gamereviews_ast_1
ner:
  Corpus: CONLL_03_GERMAN
  tag_dictionary: resources/taggers/ner_tags.pkl
target_dir: resources/taggers/
targets: ast
teacher_annealing: false
train:
  controller_momentum: 0.9
  learning_rate: 0.1
  max_episodes: 30
  max_epochs: 300
  max_epochs_without_improvement: 25
  mini_batch_size: 32
  monitor_test: false
  patience: 5
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
  use_warmup: false
trainer: ReinforcementTrainer
upos:
  Corpus: UD_GERMAN:UD_ENGLISH:UD_CZECH
  tag_dictionary: resources/taggers/pos_tags.pkl
