"""core models for review scraping and analysis

Revision ID: fd86997cda18
Revises: 57b460a916d4
Create Date: 2022-11-07 00:17:44.244832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd86997cda18'
down_revision = '57b460a916d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('steam_app_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('release_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metacritic_user_reviews_url', sa.String(), nullable=True),
    sa.Column('gamespot_review_url', sa.String(), nullable=True),
    sa.Column('gamespot_user_reviews_url', sa.String(), nullable=True),
    sa.Column('metacritic_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gamespot_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steam_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('info_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=False)
    op.create_index(op.f('ix_game_steam_app_id'), 'game', ['steam_app_id'], unique=True)
    op.create_table('reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=True),
    sa.Column('num_steam_reviews', sa.Integer(), nullable=True),
    sa.Column('num_steam_games_owned', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_id'), 'reviewer', ['id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('review', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('helpful_score', sa.String(), nullable=True),
    sa.Column('good', sa.TEXT(), nullable=True),
    sa.Column('bad', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apect_sum_polarity', sa.String(), nullable=True),
    sa.Column('playtime_forever', sa.Integer(), nullable=True),
    sa.Column('playtime_last_two_weeks', sa.Integer(), nullable=True),
    sa.Column('playtime_at_review', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['reviewer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_table('aspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('polarity', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aspect_id'), 'aspect', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aspect_id'), table_name='aspect')
    op.drop_table('aspect')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_reviewer_id'), table_name='reviewer')
    op.drop_table('reviewer')
    op.drop_index(op.f('ix_game_steam_app_id'), table_name='game')
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
