"""added unqiue contraints for aspect, analyzedreview, analyzedreviewsentence

Revision ID: 8818d4711d6f
Revises: e199a8e2993c
Create Date: 2023-04-08 16:53:28.061563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8818d4711d6f'
down_revision = 'e199a8e2993c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'analyzedreview', ['review_id', 'model', 'task'])
    op.create_unique_constraint(None, 'aspect', ['review_id', 'model_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aspect', type_='unique')
    op.drop_constraint(None, 'analyzedreview', type_='unique')
    # ### end Alembic commands ###
