"""added aggregates to sqlalchemy models

Revision ID: 4d1592e53386
Revises: 29827f1edc14
Create Date: 2023-02-20 20:42:37.348685

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = '4d1592e53386'
down_revision = '29827f1edc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game',
                  sa.Column('num_reviews', sa.Integer(), nullable=True))
    op.add_column('source',
                  sa.Column('num_reviews', sa.Integer(), nullable=True))

    op.add_column('review',
                  sa.Column('num_aspects', sa.Integer(), nullable=True),
                  )
    op.add_column('review',
                  sa.Column('num_positive_aspects', sa.Integer(), nullable=True)
                  )
    op.add_column('review',
                  sa.Column('num_negative_aspects', sa.Integer(), nullable=True)
                  )
    op.add_column('review',
                  sa.Column('num_neutral_aspects', sa.Integer(), nullable=True)
                  )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'num_reviews')
    op.drop_column('source', 'num_reviews')
    op.drop_column('review', 'num_aspects')
    op.drop_column('review', 'num_positive_aspects')
    op.drop_column('review', 'num_negative_aspects')
    op.drop_column('review', 'num_neutral_aspects')
    # ### end Alembic commands ###
