"""added analyzed review and analyzed sentence models

Revision ID: ff406bcbdbb0
Revises: 25ab1316f0fe
Create Date: 2023-04-07 14:29:50.731404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff406bcbdbb0'
down_revision = '25ab1316f0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzedreview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('cleaned_text', sa.TEXT(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('gold_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzedreview_id'), 'analyzedreview', ['id'], unique=False)
    op.create_table('analyzedreviewsentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyzed_review_id', sa.Integer(), nullable=True),
    sa.Column('sentence', sa.TEXT(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('gold_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_review_id'], ['analyzedreview.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzedreviewsentence_id'), 'analyzedreviewsentence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyzedreviewsentence_id'), table_name='analyzedreviewsentence')
    op.drop_table('analyzedreviewsentence')
    op.drop_index(op.f('ix_analyzedreview_id'), table_name='analyzedreview')
    op.drop_table('analyzedreview')
    # ### end Alembic commands ###
