"""added models: Developer and GameDeveloper(secondary table for relationship between Game <-> Developer)

Revision ID: f8729516b12c
Revises: 4d1592e53386
Create Date: 2023-03-05 19:38:06.409460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8729516b12c'
down_revision = '4d1592e53386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_id'), 'developer', ['id'], unique=False)
    op.create_index(op.f('ix_developer_name'), 'developer', ['name'], unique=False)
    op.create_table('gamedeveloper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamedeveloper_id'), 'gamedeveloper', ['id'], unique=False)
    op.drop_column('review', 'num_neutral_aspects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('num_neutral_aspects', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gamedeveloper_id'), table_name='gamedeveloper')
    op.drop_table('gamedeveloper')
    op.drop_index(op.f('ix_developer_name'), table_name='developer')
    op.drop_index(op.f('ix_developer_id'), table_name='developer')
    op.drop_table('developer')
    # ### end Alembic commands ###
