"""renamed column of Aspect table confidence->opinion

Revision ID: e199a8e2993c
Revises: ff406bcbdbb0
Create Date: 2023-04-08 16:25:34.933868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e199a8e2993c'
down_revision = 'ff406bcbdbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspect', sa.Column('opinion', sa.String(), nullable=True))
    op.drop_column('aspect', 'confidence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspect', sa.Column('confidence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('aspect', 'opinion')
    # ### end Alembic commands ###
