"""Added columns to GameSource to track reviews scraping

Revision ID: 25ab1316f0fe
Revises: f8729516b12c
Create Date: 2023-03-08 00:16:59.829884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ab1316f0fe'
down_revision = 'f8729516b12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesource', sa.Column('reviews_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('gamesource', sa.Column('num_reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamesource', 'num_reviews')
    op.drop_column('gamesource', 'reviews_scraped_at')
    # ### end Alembic commands ###
